# Generated by Django 5.0.7 on 2025-02-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_orders', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='passenger',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_orders', to='api.user'),
        ),
    ]
