# Generated by Django 5.0.7 on 2025-02-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_shipper_alter_order_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_orders', to='api.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_orders', to='api.user'),
        ),
    ]
